// This file is autogenerated by pioasm version 2.2.0; do not edit!

//go:build rp
package wavegen
import (
	pio "github.com/tinygo-org/pio/rp2-pio"
)
// cutout

const cutoutWrapTarget = 5
const cutoutWrap = 12

var cutoutInstructions = []uint16{
		0xe02d, //  0: set    x, 13
		0xa0c1, //  1: mov    isr, x
		0xe028, //  2: set    x, 8
		0x4024, //  3: in     x, 4
		0xa026, //  4: mov    x, isr
		//     .wrap_target
		0x8080, //  5: pull   noblock
		0xa047, //  6: mov    y, osr
		0x20c4, //  7: wait   1 irq, 4
		0xe001, //  8: set    pins, 1
		0x0089, //  9: jmp    y--, 9
		0xc00d, // 10: irq    prev nowait 5
		0xa242, // 11: nop                           [2]
		0xe000, // 12: set    pins, 0
		//     .wrap
}
const cutoutOrigin = -1
func cutoutProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+cutoutWrapTarget, offset+cutoutWrap)
	return cfg;
}

