// Code generated by pioasm; DO NOT EDIT.

//go:build rp
package wavegen
import (
	pio "github.com/tinygo-org/pio/rp2-pio"
)
// cutout

const cutoutWrapTarget = 0
const cutoutWrap = 9

var cutoutInstructions = []uint16{
		//     .wrap_target
		0x20c8, //  0: wait   1 irq prev, 0              
		0xff01, //  1: set    pins, 1                [31]
		0xbf42, //  2: nop                           [31]
		0xbf42, //  3: nop                           [31]
		0xbf42, //  4: nop                           [31]
		0xbf42, //  5: nop                           [31]
		0xbf42, //  6: nop                           [31]
		0xb642, //  7: nop                           [22]
		0xe000, //  8: set    pins, 0                    
		0xc009, //  9: irq    prev nowait 1              
		//     .wrap
}
const cutoutOrigin = -1
func cutoutProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+cutoutWrapTarget, offset+cutoutWrap)
	return cfg;
}

