// Code generated by pioasm; DO NOT EDIT.

//go:build rp
package wavegen
import (
	pio "github.com/tinygo-org/pio/rp2-pio"
)
const smFreq = 500_000
// wavegen

const wavegenWrapTarget = 0
const wavegenWrap = 29

var wavegenInstructions = []uint16{
		//     .wrap_target
		0xe04f, //  0: set    y, 15                      
		0xfc01, //  1: set    pins, 1                [28]
		0xfb00, //  2: set    pins, 0                [27]
		0x0081, //  3: jmp    y--, 1                     
		0xe001, //  4: set    pins, 1                    
		0xa02b, //  5: mov    x, !null                   
		0x4066, //  6: in     null, 6                    
		0x402a, //  7: in     x, 10                      
		0x4068, //  8: in     null, 8                    
		0x4028, //  9: in     x, 8                       
		0xa026, // 10: mov    x, isr                     
		0x8080, // 11: pull   noblock                    
		0x6048, // 12: out    y, 8                       
		0x0018, // 13: jmp    24                         
		0xa0c2, // 14: mov    isr, y                     
		0x0f12, // 15: jmp    18                     [15]
		0x6041, // 16: out    y, 1                       
		0x0094, // 17: jmp    y--, 20                    
		0xbc42, // 18: nop                           [28]
		0xfc00, // 19: set    pins, 0                [28]
		0xfc00, // 20: set    pins, 0                [28]
		0xf901, // 21: set    pins, 1                [25]
		0x0050, // 22: jmp    x--, 16                    
		0xa246, // 23: mov    y, isr                 [2] 
		0xe028, // 24: set    x, 8                       
		0x008e, // 25: jmp    y--, 14                    
		0xfc00, // 26: set    pins, 0                [28]
		0xec01, // 27: set    pins, 1                [12]
		0xc000, // 28: irq    nowait 0                   
		0x20c1, // 29: wait   1 irq, 1                   
		//     .wrap
}
const wavegenOrigin = -1
func wavegenProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+wavegenWrapTarget, offset+wavegenWrap)
	return cfg;
}

