// This file is autogenerated by pioasm version 2.2.0; do not edit!

//go:build rp
package wavegen
import (
	pio "github.com/tinygo-org/pio/rp2-pio"
)
// wavegen

const wavegenWrapTarget = 0
const wavegenWrap = 30

var wavegenInstructions = []uint16{
		//     .wrap_target
		0xe04f, //  0: set    y, 15
		0xfc03, //  1: set    pins, 3                [28]
		0xfb00, //  2: set    pins, 0                [27]
		0x0081, //  3: jmp    y--, 1
		0xef03, //  4: set    pins, 3                [15]
		0xa02b, //  5: mov    x, ~null
		0x4066, //  6: in     null, 6
		0x402a, //  7: in     x, 10
		0x4068, //  8: in     null, 8
		0x4028, //  9: in     x, 8
		0xa026, // 10: mov    x, isr
		0x8080, // 11: pull   noblock
		0x6048, // 12: out    y, 8
		0x0018, // 13: jmp    24
		0xa0c2, // 14: mov    isr, y
		0x0012, // 15: jmp    18
		0x6041, // 16: out    y, 1
		0x0394, // 17: jmp    y--, 20                [3]
		0xbc42, // 18: nop                           [28]
		0xfc00, // 19: set    pins, 0                [28]
		0xfc00, // 20: set    pins, 0                [28]
		0xf603, // 21: set    pins, 3                [22]
		0x0050, // 22: jmp    x--, 16
		0xa046, // 23: mov    y, isr
		0xe028, // 24: set    x, 8
		0x008e, // 25: jmp    y--, 14
		0xa142, // 26: nop                           [1]
		0xfc00, // 27: set    pins, 0                [28]
		0xea03, // 28: set    pins, 3                [10]
		0xc01c, // 29: irq    next nowait 4
		0x20c5, // 30: wait   1 irq, 5
		//     .wrap
}
const wavegenOrigin = -1
func wavegenProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+wavegenWrapTarget, offset+wavegenWrap)
	return cfg;
}

